#!/bin/bash

#Generate JAR file
./mvnw clean package -q

JAVA_OPTIONS="-Xms256m -Xmx256m -XX:NewRatio=1 -XX:+AggressiveHeap --illegal-access=warn"

if [ "$1" = "docker" ]; then
	docker build -t vertx-opensanca .
	docker run -e "JAVA_OPTS=$JAVA_OPTIONS" -p 8081:8081 vertx-opensanca:latest
else
	java -jar $JAVA_OPTIONS target/vertx-opensanca-fat.jar
fi
